export interface Room {
  id: string;
  roomNo: number;
  floor: number;
  dimension: string;
  noOfBedRoom: number;
  status: "Rented" | "Available" | "Reserved";
  sellingPrice: number;
  maxNoPeople: number;
  description: string;
}

export const mockRooms: Room[] = [
  {
    id: "r1",
    roomNo: 101,
    floor: 1,
    dimension: "20x30 ft",
    noOfBedRoom: 2,
    status: "Rented",
    sellingPrice: 50000000,
    maxNoPeople: 3,
    description: "Cozy 2-bedroom with balcony view",
  },
  {
    id: "r2",
    roomNo: 102,
    floor: 1,
    dimension: "22x32 ft",
    noOfBedRoom: 3,
    status: "Rented",
    sellingPrice: 65000000,
    maxNoPeople: 4,
    description: "Spacious corner unit",
  },
  {
    id: "r3",
    roomNo: 103,
    floor: 1,
    dimension: "18x28 ft",
    noOfBedRoom: 1,
    status: "Rented",
    sellingPrice: 40000000,
    maxNoPeople: 2,
    description: "Compact unit, ideal for single tenant",
  },
  {
    id: "r4",
    roomNo: 201,
    floor: 2,
    dimension: "25x35 ft",
    noOfBedRoom: 3,
    status: "Rented",
    sellingPrice: 70000000,
    maxNoPeople: 5,
    description: "Family-size unit with park view",
  },
  {
    id: "r5",
    roomNo: 202,
    floor: 2,
    dimension: "20x25 ft",
    noOfBedRoom: 2,
    status: "Rented",
    sellingPrice: 52000000,
    maxNoPeople: 3,
    description: "Well-lit 2-bedroom unit",
  },
  {
    id: "r6",
    roomNo: 203,
    floor: 2,
    dimension: "19x29 ft",
    noOfBedRoom: 2,
    status: "Rented",
    sellingPrice: 51000000,
    maxNoPeople: 3,
    description: "Close to elevator",
  },
  {
    id: "r7",
    roomNo: 301,
    floor: 3,
    dimension: "28x36 ft",
    noOfBedRoom: 4,
    status: "Rented",
    sellingPrice: 85000000,
    maxNoPeople: 6,
    description: "Large family unit, top corner",
  },
  {
    id: "r8",
    roomNo: 302,
    floor: 3,
    dimension: "20x30 ft",
    noOfBedRoom: 2,
    status: "Rented",
    sellingPrice: 53000000,
    maxNoPeople: 3,
    description: "Standard 2-bedroom unit",
  },
  {
    id: "r9",
    roomNo: 303,
    floor: 3,
    dimension: "24x34 ft",
    noOfBedRoom: 3,
    status: "Rented",
    sellingPrice: 67000000,
    maxNoPeople: 4,
    description: "Modern design with open kitchen",
  },
  {
    id: "r10",
    roomNo: 401,
    floor: 4,
    dimension: "18x27 ft",
    noOfBedRoom: 1,
    status: "Rented",
    sellingPrice: 39000000,
    maxNoPeople: 2,
    description: "Studio apartment",
  },
  {
    id: "r11",
    roomNo: 402,
    floor: 4,
    dimension: "21x31 ft",
    noOfBedRoom: 2,
    status: "Rented",
    sellingPrice: 54000000,
    maxNoPeople: 3,
    description: "Bright 2-bedroom with balcony",
  },
  {
    id: "r12",
    roomNo: 403,
    floor: 4,
    dimension: "26x36 ft",
    noOfBedRoom: 4,
    status: "Rented",
    sellingPrice: 88000000,
    maxNoPeople: 6,
    description: "Premium unit with city view",
  },
];
